export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';




export const GET_SCRAPERS = 'GET_SCRAPERS';
export const ADD_SCRAPER = 'ADD_SCRAPERS';
export const GET_SCRAPER = 'GET_SCRAPER';
export const DELETE_SCRAPER = 'DELETE_SCRAPER';
export const UPDATE_SCRAPER = 'UPDATE_SCRAPER';
export const SCRAPER_ERROR = 'SCRAPER_ERROR';
export const IMPORT_SCRAPER = 'IMPORT_SCRAPER';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const ASSOCIATE_SCRAPER = 'ASSOCIATE_SCRAPER';